// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both VITE_ and NEXT_PUBLIC_ prefixes for compatibility
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || import.meta.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  throw new Error(
    'Missing Supabase URL environment variable. ' +
    'Please set VITE_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_URL in your .env file or Vercel environment variables.'
  );
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase Publishable Key environment variable. ' +
    'Please set VITE_SUPABASE_PUBLISHABLE_KEY or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY in your .env file or Vercel environment variables.'
  );
}

// Validate URL format
if (!SUPABASE_URL.startsWith('http://') && !SUPABASE_URL.startsWith('https://')) {
  throw new Error(
    `Invalid Supabase URL: "${SUPABASE_URL}". ` +
    'Must be a valid HTTP or HTTPS URL.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});